Make sure there are more than 1 values in a category before rendering it
chanzuckerberg/cellxgene pull request #1871
Opened 2020-09-24 17:58 UTC by maniarathi

I also ran prettier which automatically changed `embedding.js`. There are no functional changes there.

Closes #1869

2020-09-28 17:59 UTC, seve requested changes

2020-09-28 17:59 UTC, seve commented on client/src/components/categorical/index.js
> +          schema.annotations.obsByName[catName].categories.length > 1 ? (
```suggestion
          schema.annotations.obsByName[catName].writable ? (
```

We still want to display single value user annos in the left sidebar

2020-09-28 17:59 UTC, seve commented on client/src/components/categorical/index.js
> +          schema.annotations.obsByName[catName].categories.length > 1 ? (
Categories might not be defined for the category

```suggestion
          !schema.annotations.obsByName[catName].writable &&
          schema.annotations.obsByName[catName].categories?.length > 1 ? (
```

2020-09-28 18:07 UTC, seve commented on client/src/components/categorical/index.js
> +          schema.annotations.obsByName[catName].categories.length > 1 ? (
Actually my fix is not correct, we want categories with undefined `categories` values to pass through to render:

```suggestion
          !schema.annotations.obsByName[catName].writable &&
          (schema.annotations.obsByName[catName].categories?.length > 1 ||
            !schema.annotations.obsByName[catName].categories) ? (
```

2020-09-29 00:52 UTC, maniarathi commented
Addressed the suggested changes!

2020-09-29 00:52 UTC, maniarathi commented
I also tested these changes on a 4M dataset to ensure that it still worked.

2020-09-29 21:50 UTC, seve approved these changes
LGTM!

2020-09-29 22:32 UTC, merged