Thuang update gha unit test and add make lint client
chanzuckerberg/cellxgene pull request #2356
Opened 2021-07-30 03:55 UTC by tihuan

#### Reviewers
**Functional:** 
@bkmartinjr 

**Readability:** 
@seve @MDunitz 
---

## Changes
1.  Change unit test GHA to run `make unit-test` instead of `make unit-test-server`, so we run `unit-test-server unit-test-client unit-test-common` as expected
2.  Add back `make lint` in client `Makefile`, so root `make lint` will trigger lint for both server and client!
3. Ran `make lint` and it formatted some python files 👌

2021-07-30 14:46 UTC, bkmartinjr commented on backend/common/fbs/NetEncoding/Column.py
>  import flatbuffers
Do not reformat the contents of the `fbs/NetEncoding` directory - they are machine generated.

2021-07-30 14:48 UTC, bkmartinjr commented
This PR should not reformat any Python, as it is a f/e lint change.

2021-07-30 15:02 UTC, bkmartinjr requested changes
Several requests:
1. we need to cleanly separate the `lint` and `fmt` commands. They should use the same configuration, but IMHO, `lint` is a read-only error check (pass/fail, no code mods), while `fmt` will auto-format the code
2. Please do _not_ reformat Python in this PR.  This is a front-end only PR and should have no impact on the Python code.

2021-08-18 15:30 UTC, closed without merging

2021-08-18 15:31 UTC, tihuan commented
Will open a new one after the repo split! Thank you!