Types for /util
chanzuckerberg/cellxgene pull request #2370
Opened 2021-08-06 22:48 UTC by colinmegill

Adding typescript types to `src/util` folder

2021-08-09 19:09 UTC, tihuan commented on client/src/util/clip.ts
> +  setTo: number | undefined
shortcut for `number | undefined` is `setTo?: number` 🙆‍♂️

2021-08-09 19:11 UTC, tihuan reviewed
Typings look great! Thanks so much, @colinmegill 🎉 !

Can we also update the call sites that use these functions too? (Removing `eslint-disable` at the call sites 🙏 )

Thank you!

2021-08-09 21:16 UTC, seve requested changes

2021-08-09 21:16 UTC, seve commented on client/src/util/catLabelSort.ts
> +function caseInsensitiveCompare(a: string, b: string) {
We'll want to also be typing the return type

2021-08-09 21:48 UTC, tihuan commented
@seve actually Brian just reminded me that Colin is out this week. So can you help take over this PR 😆 ? Thank you so much!!

2021-08-10 22:55 UTC, MillenniumFalconMechanic commented
Hi @colinmegill, typings are looking good!

I am seeing and couple of compile errors when I run `npm run type-check` and lint errors when I run `npm run lint` locally:

#### npm run type-check
```
src/util/finiteExtent.ts:26:11 - error TS2532: Object is possibly 'undefined'.

26       if (min > val) min = val;
             ~~~

src/util/finiteExtent.ts:27:11 - error TS2532: Object is possibly 'undefined'.

27       if (max < val) max = val;
             ~~~

src/util/parseRGB.ts:27:12 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.

27   let cv = colorCache[c];
              ~~~~~~~~~~~~~

src/util/parseRGB.ts:30:5 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.

30     colorCache[c] = cv;
```

#### npm run lint

```
/Users/mim/git/cellxgene/client/src/util/clip.ts
  13:16  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/Users/mim/git/cellxgene/client/src/util/finiteExtent.ts
  9:1  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/Users/mim/git/cellxgene/client/src/util/parseBulkGeneString.ts
  9:16  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/Users/mim/git/cellxgene/client/src/util/parseRGB.ts
  26:16  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/Users/mim/git/cellxgene/client/src/util/scaleLinear.ts
  9:16  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/Users/mim/git/cellxgene/client/src/util/scaleRGB.ts
  1:16  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
```

Are you able to see these errors and warnings with your setup?

Finally, I see there are a couple of remaining `any` error suppressions; I wanted to check if these are OK as is for this PR (and we can just update them iteratively going forward).

2021-08-11 16:47 UTC, tihuan commented
OK looks like the linter is failing as expected now 💪

2021-08-16 17:54 UTC, closed without merging