move common code into server, update tests and makefile
chanzuckerberg/cellxgene pull request #2425
Opened 2021-09-13 21:14 UTC by MDunitz

#### Reviewers
**Functional:** 

**Readability:** 

---

## Changes
- add
- remove
- modify

2021-09-14 22:01 UTC, bkmartinjr commented on .dockerignore
>  docs
does this need to have `server` added?  (I am not expert on our docker config)

2021-09-14 22:21 UTC, maniarathi commented on Makefile
>  copy-client-assets-czi-hosted:
Can be deleted?

2021-09-14 22:26 UTC, bkmartinjr commented on test/locust/README.md
> +This directory contains scripts to load test cellxgene's  It
missing word...   I'm not sure you intended to delete this `backend` :-)

2021-09-14 22:29 UTC, bkmartinjr commented on test/unit/converters/schema/test_validate.py
> +        self.source_h5ad_path = f"{PROJECT_ROOT}/test/fixtures/pbmc3k-CSC-gz.h5ad"
FIXTURES_ROOT?

2021-09-14 22:29 UTC, bkmartinjr requested changes
comments:

1. Do you also need to update the following files?
    * `.bumpversion.cfg`
    * `compatibility_tests.yml`
    * `push_tests.yml`

2. The following fails on my box (I think it used to work) - at top levek, run the following commands, and the last one (unit-test) fails:
    * make build-for-server-dev
    * pip install -e .
    * make unit-test 

     The unit test fails in the _client_ unit tests.  The actual cellxgene build works fine.

3. couple of other tiny nits inline

2021-09-14 23:00 UTC, MDunitz commented
> comments:
> 
> 1. Do you also need to update the following files?
>    
>    * `.bumpversion.cfg`
>    * `compatibility_tests.yml`
>    * `push_tests.yml`

Yes
> 2. The following fails on my box (I think it used to work) - at top levek, run the following commands, and the last one (unit-test) fails:
>    
>    * make build-for-server-dev
>    * pip install -e .
>    * make unit-test
>    
>    The unit test fails in the _client_ unit tests.  The actual cellxgene build works fine.

Updated, they currently work locally for me but please let me know if they still dont work for you
> 3. couple of other tiny nits inline

2021-09-15 00:33 UTC, bkmartinjr commented on test/locust/README.md
> +This directory contains scripts to load test cellxgene's  It
still not fixed

2021-09-15 00:37 UTC, bkmartinjr commented
> > The unit test fails in the client unit tests. The actual cellxgene build works fine.
> 
> Updated, they currently work locally for me but please let me know if they still dont work for you

It still fails for me.  I did from top-level:
1. make clean
2. make build-for-server-dev
3. pip install -e .
4. make unit-test

It fails.  Is it related to #2428 ?


Errors:

```

Summary of all failing tests
 FAIL  __tests__/util/annoMatrix/annoMatrix.test.js
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      1 | export const baseDataURL = "https://a.fake.url/api/v0.2";
      2 |
    > 3 | window.CELLXGENE = {
        | ^
      4 |   API: {
      5 |     prefix: baseDataURL,
      6 |     version: "v0.2/",

      at Object.<anonymous> (__tests__/util/annoMatrix/serverMocks/index.js:3:1)
      at Object.<anonymous> (__tests__/util/annoMatrix/annoMatrix.test.js:3:1)

 FAIL  __tests__/util/annoMatrix/crossfilter.test.js
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      1 | export const baseDataURL = "https://a.fake.url/api/v0.2";
      2 |
    > 3 | window.CELLXGENE = {
        | ^
      4 |   API: {
      5 |     prefix: baseDataURL,
      6 |     version: "v0.2/",

      at Object.<anonymous> (__tests__/util/annoMatrix/serverMocks/index.js:3:1)
      at Object.<anonymous> (__tests__/util/annoMatrix/crossfilter.test.js:3:1)

 FAIL  __tests__/util/actionHelpers.test.js
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      3 | /** Singleton toaster instance. Create separate instances for different options. */
      4 |
    > 5 | const ToastTopCenter = Toaster.create({
        |                                ^
      6 |   className: "recipe-toaster",
      7 |   position: Position.TOP,
      8 |   maxToasts: 4,

      at Function.create (node_modules/@blueprintjs/core/src/components/toast/toaster.tsx:126:49)
      at Object.<anonymous> (src/components/framework/toasters.js:5:32)
      at Object.<anonymous> (src/util/actionHelpers.js:3:1)

 FAIL  __tests__/util/annoMatrix/whereCache.test.js
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      3 | /** Singleton toaster instance. Create separate instances for different options. */
      4 |
    > 5 | const ToastTopCenter = Toaster.create({
        |                                ^
      6 |   className: "recipe-toaster",
      7 |   position: Position.TOP,
      8 |   maxToasts: 4,

      at Function.create (node_modules/@blueprintjs/core/src/components/toast/toaster.tsx:126:49)
      at Object.<anonymous> (src/components/framework/toasters.js:5:32)
      at Object.<anonymous> (src/util/actionHelpers.js:3:1)

 FAIL  __tests__/util/centroid.test.js
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      3 | /** Singleton toaster instance. Create separate instances for different options. */
      4 |
    > 5 | const ToastTopCenter = Toaster.create({
        |                                ^
      6 |   className: "recipe-toaster",
      7 |   position: Position.TOP,
      8 |   maxToasts: 4,

      at Function.create (node_modules/@blueprintjs/core/src/components/toast/toaster.tsx:126:49)
      at Object.<anonymous> (src/components/framework/toasters.js:5:32)
      at Object.<anonymous> (src/util/actionHelpers.js:3:1)

 FAIL  __tests__/util/stateManager/colorHelpers.test.js
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      3 | /** Singleton toaster instance. Create separate instances for different options. */
      4 |
    > 5 | const ToastTopCenter = Toaster.create({
        |                                ^
      6 |   className: "recipe-toaster",
      7 |   position: Position.TOP,
      8 |   maxToasts: 4,

      at Function.create (node_modules/@blueprintjs/core/src/components/toast/toaster.tsx:126:49)
      at Object.<anonymous> (src/components/framework/toasters.js:5:32)
      at Object.<anonymous> (src/util/actionHelpers.js:3:1)

 FAIL  __tests__/reducers/genesets.test.js
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

      3 | /** Singleton toaster instance. Create separate instances for different options. */
      4 |
    > 5 | const ToastTopCenter = Toaster.create({
        |                                ^
      6 |   className: "recipe-toaster",
      7 |   position: Position.TOP,
      8 |   maxToasts: 4,

      at Function.create (node_modules/@blueprintjs/core/src/components/toast/toaster.tsx:126:49)
      at Object.<anonymous> (src/components/framework/toasters.js:5:32)
      at Object.<anonymous> (src/util/actionHelpers.js:3:1)


Test Suites: 7 failed, 17 passed, 24 total
Tests:       213 passed, 213 total
Snapshots:   0 total
Time:        2.24 s, estimated 4 s
Ran all test suites.
make[1]: *** [Makefile:58: unit-test] Error 1
make[1]: Leaving directory '/home/bruce/projects/cellxgene/client'
make: *** [Makefile:62: unit-test-client] Error 2
```

2021-09-20 23:00 UTC, bkmartinjr approved these changes
LGTM

2021-09-20 23:26 UTC, atolopko-czi commented on server/Makefile
> +	python ../test/performance/performance_test_annotations_py
file extension: `.py`

2021-09-20 23:52 UTC, atolopko-czi commented on server/__main__.py
> +    pdb.set_trace()
debug code to remove

2021-09-20 23:52 UTC, MDunitz commented on server/Makefile
> +	python ../test/performance/performance_test_annotations_py
```suggestion
	python ../test/performance/performance_test_annotations.py
```

2021-09-20 23:53 UTC, MDunitz commented on server/__main__.py
> +    import pdb
```suggestion
```

2021-09-20 23:54 UTC, MDunitz commented on server/__main__.py
> +    pdb.set_trace()
```suggestion
```

2021-09-21 00:12 UTC, atolopko-czi approved these changes
LGTM. `cellxgene` install and runs, and unit tests pass for me (with the exception of `colorHelpers.test.js`, which I've never seen run to completion on my localhost!).

2021-09-21 00:13 UTC, atolopko-czi commented
`Code scanning results / CodeQL` check fails, but it looks like it can be ignored since it's in test code?

2021-09-21 01:50 UTC, merged